# Set Travis-CI build language to JavaScript (with NodeJS)
language: node_js

# Switch Sudo off to use Travi's new and fast Docker infrastructure
sudo: false

# Make sure `grunt-cli` is installed, and project is built after `npm install` is run by Travis-CI
before_script:
  - npm install -g grunt-cli
  - grunt build
